FROM postgres:16

# Copy the custom restore script into the container
COPY restore.sh /usr/local/bin/restore.sh
RUN chmod +x /usr/local/bin/restore.sh

# Set the entrypoint to the custom script
ENTRYPOINT ["/usr/local/bin/restore.sh"]

