services:
  soa_backend:
    build: ./backend
    container_name: soa_backend
    ports:
      - "5000:5000"
    depends_on:
      - soa_postgres_db
    environment:
      - DB_HOST=soa_postgres_db
      - DB_PORT=5432
      - DB_USER=backend
      - DB_PASSWORD=backend
      - DB_NAME=backend
    restart: always

  soa_postgres_db:
    image: postgres:16
    container_name: soa_postgres_db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend
      POSTGRES_DB: backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  soa_redis:
    image: "redis:alpine"
    container_name: soa_redis
    command: redis-server
    ports:
      - 6379:6379
    expose:
      - "6379"
    restart: unless-stopped
  
  soa_keycloak:
    image: quay.io/keycloak/keycloak
    container_name: soa_keycloak
    ports:
      - "8080:8080"
    command: 
      - start-dev
      - --hostname=https://x.devgains.com/auth
      - --proxy=edge
      #- --hostname-path=/auth
      - --proxy-headers=xforwarded
      - --hostname-strict=false
      #- --optimized
      - --verbose

    environment:
      KC_HOSTNAME: localhost # to be accessed from the host machine
      KC_HOSTNAME_PORT: 8080
      # Database configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://soa_keycloak_db/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak  
      # Keycloak configuration
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      # Admin user configuration
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # proxy mode
      #PROXY_ADDRESS_FORWARDING: true 
      #KC_PROXY: edge
    depends_on:
       -  soa_keycloak_db
    restart: unless-stopped


  soa_keycloak_db:
  # Do not expose this container port to the outside world for security reasons
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: soa_keycloak_db
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
        - ./keycloak_backup:/docker-entrypoint-initdb.d
 
    restart: unless-stopped


  soa_apache:
    build:
      context: .
      dockerfile: Dockerfile.apache.ext
    container_name: soa_apache
    ports:
    - "443:443"
    depends_on:
     - soa_backend
     - soa_keycloak
    restart: unless-stopped

#  nginx:
#    build : ./nginx-configs
#    container_name: nginx
#    depends_on:
#      - soa_backend
#      - soa_keycloak
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx-configs/default.conf:/etc/nginx.conf:ro
#      - ./certs/birder.epita.fr.crt:/etc/nginx/ssl/server.crt:ro
#      - ./certs/birder.epita.fr.key:/etc/nginx/ssl/server.key:ro
#    restart: always

volumes:
  pgdata: